[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tspng"
version = "1.1.0"
authors = [
  { name="Theia Scientific", email="support@theiascientific.com" },
]
description = "A Python package for manipulating PNG files with embedded JSON related to Machine Learning."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Image Recognition",
]
dependencies = ["Pillow"]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
"Homepage" = "https://github.com/Theia-Scientific/tspng"
"Bug Tracker" = "https://github.com/Theia-Scientific/tspng/issues"

[project.scripts]
tspng = "tspng.cli:app"

[project.optional-dependencies]
dev = [
  "black",
  "build",
  "flake8",
  "hatch",
  "isort",
  "pytest",
  "pytest-cov",
  "pytest-mock",
  "twine"
]
cli = ["typer"]

[tool.coverage.report]
exclude_lines = [ "if __name__ == .__main__.:" ]
omit = [ "__main__.py" ]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
]

[tool.flake8]
ignore = ['E203', 'W503']
max-line-length = 127
max-complexity = 15
