#!/usr/bin/env python3

import io
import json
import pytest

from datetime import datetime as DateTime
from pathlib import Path
from PIL import Image
from PIL.PngImagePlugin import PngImageFile
from pytest_mock import MockerFixture
from tspng.schema import coco, generic, text
from tspng.schema.data import Embedded, Meta as Metadata, MetadataNotFound, NotPngFormat
from tspng.schema.ts import FILE_EXT as TS_FILE_EXT, MIME_TYPE as TS_MIME_TYPE, v1, v2
from typing import Any, Callable


@pytest.fixture
def empty_jpeg_path(tmp_path: Path) -> Path:
    empty_jpeg_path = tmp_path.joinpath("empty.jpeg")
    image = Image.new("RGB", (640, 640))
    image.save(empty_jpeg_path, format="JPEG")
    return empty_jpeg_path


@pytest.fixture
def mock_metadata() -> Callable[[str, str], Metadata]:
    def create_metadata(
        data: str,
        creation_time: DateTime | str = "20260910T121212.000Z",
        mime_type: str = text.MIME_TYPE,
    ) -> Metadata:
        return Metadata(
            author="Tester",
            comment="This is a comment",
            description="This is a description",
            copyright="This is something about copyright",
            creation_time=creation_time,
            disclaimer="I have no responsibility",
            embedded=[
                Embedded.model_validate(
                    {
                        "data": data,
                        "mime_type": mime_type,
                    }
                )
            ],
            title="This is a Title",
            software="Generated by some software",
            source="This test",
        )

    return create_metadata


def test_coco_json(coco_json_path: Path):
    with open(coco_json_path) as f:
        result = coco.Json.model_validate_json(f.read())
    assert isinstance(result, coco.Json)


def test_ts_v1_legacy_json(ts_v1_legacy_json_path: Path):
    with open(ts_v1_legacy_json_path) as f:
        result = v1.Json.model_validate_json(f.read())
    assert isinstance(result, v1.Json)


def test_ts_v1_modern_json(ts_v1_modern_json_path: Path):
    with open(ts_v1_modern_json_path) as f:
        result = v1.Json.model_validate_json(f.read())
    assert isinstance(result, v1.Json)


def test_ts_v2_json(ts_v2_json_path: Path):
    with open(ts_v2_json_path) as f:
        result = v2.Json.model_validate_json(f.read())
    assert isinstance(result, v2.Json)


def test_embedded_generic_json():
    data = {"greeting": "Hello", "target": "World"}
    embedded: dict[str, generic.Json | str] = {
        "data": data,
        "mime_type": generic.MIME_TYPE,
    }
    result = Embedded.model_validate(embedded)
    assert isinstance(result, Embedded)
    assert result.mime_type == generic.MIME_TYPE
    assert isinstance(result.data, dict)
    assert result.text == json.dumps(result.data)
    assert result.ext == generic.FILE_EXT
    result = Embedded(data=data, mime_type=generic.MIME_TYPE)
    assert isinstance(result, Embedded)
    assert result.mime_type == generic.MIME_TYPE
    assert isinstance(result.data, dict)
    assert result.text == json.dumps(result.data)
    assert result.ext == generic.FILE_EXT
    result = Embedded(data=data)
    assert isinstance(result, Embedded)
    assert result.mime_type == generic.MIME_TYPE
    assert isinstance(result.data, dict)
    assert result.text == json.dumps(result.data)
    assert result.ext == generic.FILE_EXT


def test_embedded_ts_v1_modern_json(ts_v1_modern_json_path: Path):
    with open(ts_v1_modern_json_path) as f:
        data = json.load(f)
    embedded: dict[str, dict[str, Any] | str] = {
        "data": data,
        "mime_type": TS_MIME_TYPE,
    }
    result = Embedded.model_validate(embedded)
    assert isinstance(result, Embedded)
    assert result.mime_type == TS_MIME_TYPE
    assert isinstance(result.data, v1.Json)
    assert result.text == result.data.model_dump_json()
    assert result.ext == TS_FILE_EXT
    result = Embedded(data=data, mime_type=TS_MIME_TYPE)
    assert isinstance(result, Embedded)
    assert result.mime_type == TS_MIME_TYPE
    assert isinstance(result.data, v1.Json)
    assert result.text == result.data.model_dump_json()
    assert result.ext == TS_FILE_EXT
    result = Embedded(data=data)
    assert isinstance(result, Embedded)
    assert result.mime_type == TS_MIME_TYPE
    assert isinstance(result.data, v1.Json)
    assert result.text == result.data.model_dump_json()
    assert result.ext == TS_FILE_EXT


def test_embedded_ts_v1_legacy_json(ts_v1_legacy_json_path: Path):
    with open(ts_v1_legacy_json_path) as f:
        data = json.load(f)
    embedded: dict[str, dict[str, Any] | str] = {
        "data": data,
        "mime_type": TS_MIME_TYPE,
    }
    result = Embedded.model_validate(embedded)
    assert isinstance(result, Embedded)
    assert result.mime_type == TS_MIME_TYPE
    assert isinstance(result.data, v1.Json)
    assert result.text == result.data.model_dump_json()
    assert result.ext == TS_FILE_EXT
    result = Embedded(data=data, mime_type=TS_MIME_TYPE)
    assert isinstance(result, Embedded)
    assert result.mime_type == TS_MIME_TYPE
    assert isinstance(result.data, v1.Json)
    assert result.text == result.data.model_dump_json()
    assert result.ext == TS_FILE_EXT
    result = Embedded(data=data)
    assert isinstance(result, Embedded)
    assert result.mime_type == TS_MIME_TYPE
    assert isinstance(result.data, v1.Json)
    assert result.text == result.data.model_dump_json()
    assert result.ext == TS_FILE_EXT


def test_embedded_coco_json(coco_json_path: Path):
    with open(coco_json_path) as f:
        data = json.load(f)
    embedded: dict[str, dict[str, Any] | str] = {
        "data": data,
        "mime_type": coco.MIME_TYPE,
    }
    result = Embedded.model_validate(embedded)
    assert isinstance(result, Embedded)
    assert result.mime_type == coco.MIME_TYPE
    assert isinstance(result.data, coco.Json)
    assert result.text == result.data.model_dump_json()
    assert result.ext == coco.FILE_EXT
    result = Embedded(data=data, mime_type=coco.MIME_TYPE)
    assert isinstance(result, Embedded)
    assert result.mime_type == coco.MIME_TYPE
    assert isinstance(result.data, coco.Json)
    assert result.text == result.data.model_dump_json()
    assert result.ext == coco.FILE_EXT
    result = Embedded(data=data)
    assert isinstance(result, Embedded)
    assert result.mime_type == coco.MIME_TYPE
    assert isinstance(result.data, coco.Json)
    assert result.text == result.data.model_dump_json()
    assert result.ext == coco.FILE_EXT


def test_embedded_text():
    data = "Hello, World!"
    embedded: dict[str, str] = {
        "data": data,
        "mime_type": text.MIME_TYPE,
    }
    result = Embedded.model_validate(embedded)
    assert isinstance(result, Embedded)
    assert result.mime_type == text.MIME_TYPE
    assert isinstance(result.data, str)
    assert result.text == result.data
    assert result.ext == text.FILE_EXT
    result = Embedded(data=data, mime_type=text.MIME_TYPE)
    assert isinstance(result, Embedded)
    assert result.mime_type == text.MIME_TYPE
    assert isinstance(result.data, str)
    assert result.text == result.data
    assert result.ext == text.FILE_EXT
    result = Embedded(data=data)
    assert isinstance(result, Embedded)
    assert result.mime_type == text.MIME_TYPE
    assert isinstance(result.data, str)
    assert result.text == result.data
    assert result.ext == text.FILE_EXT


def test_embedded_load_text(txt_file_path: Path):
    result = Embedded.load(txt_file_path)
    assert isinstance(result, Embedded)
    assert result.mime_type == text.MIME_TYPE
    assert isinstance(result.data, str)
    assert result.text == result.data
    assert result.ext == text.FILE_EXT


def test_embedded_load_fails_file_not_exists(tmp_path: Path):
    with pytest.raises(FileNotFoundError):
        _ = Embedded.load(tmp_path.joinpath("random.png"))


def test_embedded_load_fails_path_not_file(tmp_path: Path):
    with pytest.raises(IsADirectoryError):
        _ = Embedded.load(tmp_path)


def test_embedded_dump_to_file(
    coco_json_path: Path,
    txt_file_path: Path,
    ts_v1_legacy_json_path: Path,
    tmp_path: Path,
):
    with open(coco_json_path) as f:
        coco_data = json.load(f)
    coco_dst = tmp_path.joinpath("coco.json")
    actual = Embedded(data=coco_data).dump(coco_dst)
    assert coco_dst.exists()
    expected = Embedded.load(coco_dst)
    assert actual == expected

    with open(ts_v1_legacy_json_path) as f:
        v1_data = json.load(f)
    v1_dst = tmp_path.joinpath("v1.json")
    actual = Embedded(data=v1_data).dump(v1_dst)
    assert v1_dst.exists()
    expected = Embedded.load(v1_dst)
    assert actual == expected

    generic_data = {"greeting": "Hello", "target": "World"}
    generic_dst = tmp_path.joinpath("generic.json")
    _ = Embedded(data=generic_data).dump(generic_dst)
    assert generic_dst.exists()
    with open(generic_dst) as f:
        assert json.load(f) == generic_data

    with open(txt_file_path) as f:
        text_data = f.read()
    text_dst = tmp_path.joinpath("text.txt")
    _ = Embedded(data=text_data).dump(text_dst)
    assert text_dst.exists()
    with open(text_dst) as f:
        assert f.read() == text_data


def test_embedded_dump_to_buffer(
    coco_json_path: Path, txt_file_path: Path, ts_v1_legacy_json_path: Path
):
    with open(coco_json_path) as f:
        coco_data = json.load(f)
    coco_dst = io.StringIO()
    actual = Embedded(data=coco_data).dump(coco_dst)
    expected = Embedded.load(coco_dst)
    assert actual == expected

    with open(ts_v1_legacy_json_path) as f:
        v1_data = json.load(f)
    v1_dst = io.StringIO()
    actual = Embedded(data=v1_data).dump(v1_dst)
    expected = Embedded.load(v1_dst)
    assert actual == expected

    generic_data = {"greeting": "Hello", "target": "World"}
    generic_dst = io.StringIO()
    _ = Embedded(data=generic_data).dump(generic_dst)
    assert json.loads(generic_dst.getvalue()) == generic_data

    with open(txt_file_path) as f:
        text_data = f.read()
    text_dst = io.StringIO()
    _ = Embedded(data=text_data).dump(text_dst)
    assert text_dst.getvalue() == text_data


def test_metadata_datetime_creation_time(empty_png_path: Path, mock_metadata):
    data = "Hello, World!"
    now = DateTime.now()
    metadata = mock_metadata(data, creation_time=now)
    im = Image.open(empty_png_path)
    im.save(empty_png_path, format="PNG", pnginfo=metadata.png_info)
    im.close()
    saved_im = Image.open(empty_png_path)
    assert isinstance(saved_im, PngImageFile)
    meta = saved_im.text
    assert meta is not None
    keys = meta.keys()
    assert "Creation Time" in keys
    actual = meta["Creation Time"]
    assert len(actual) > 0
    assert actual == now.strftime("%Y-%m-%dT%H:%M:%S.%f%z")


def test_metadata(empty_png_path: Path, mock_metadata):
    data = "Hello, World!"
    metadata = mock_metadata(data)
    im = Image.open(empty_png_path)
    im.save(empty_png_path, format="PNG", pnginfo=metadata.png_info)
    im.close()
    saved_im = Image.open(empty_png_path)
    assert isinstance(saved_im, PngImageFile)
    meta = saved_im.text
    assert meta is not None
    keys = meta.keys()
    assert "Author" in keys
    assert "Comment" in keys
    assert "Copyright" in keys
    assert "Creation Time" in keys
    assert "Description" in keys
    assert "Disclaimer" in keys
    assert "Title" in keys
    assert "Software" in keys
    assert "Source" in keys
    assert text.MIME_TYPE in keys
    result = meta[text.MIME_TYPE]
    assert result == data


def test_metadata_extra_keys(empty_png_path: Path, mock_metadata):
    data = "Hello, World!"
    info = mock_metadata(data).png_info
    info.add_text("Location", "New York City")
    info.add_text("Extra", "Some other text")
    im = Image.open(empty_png_path)
    im.save(empty_png_path, format="PNG", pnginfo=info)
    im.close()
    saved_im = Image.open(empty_png_path)
    assert isinstance(saved_im, PngImageFile)
    meta = saved_im.text
    assert meta is not None
    keys = meta.keys()
    assert "Author" in keys
    assert "Comment" in keys
    assert "Copyright" in keys
    assert "Creation Time" in keys
    assert "Description" in keys
    assert "Disclaimer" in keys
    assert "Title" in keys
    assert "Software" in keys
    assert "Source" in keys
    assert "Location" in keys
    assert "Extra" in keys
    assert text.MIME_TYPE in keys
    result = Metadata.load(empty_png_path)
    assert result.author == meta["Author"]
    assert result.comment == meta["Comment"]
    assert result.copyright == meta["Copyright"]
    assert result.creation_time == meta["Creation Time"]
    assert result.description == meta["Description"]
    assert result.disclaimer == meta["Disclaimer"]
    assert result.title == meta["Title"]
    assert result.software == meta["Software"]
    assert result.source == meta["Source"]
    assert len(result.embedded) == 1
    assert result.embedded[0].mime_type == text.MIME_TYPE
    assert result.embedded[0].data == data


def test_metadata_load_not_png_fails(empty_jpeg_path: Path):
    with pytest.raises(NotPngFormat):
        _ = Metadata.load(empty_jpeg_path)


def test_metadata_load_no_metadata(empty_png_path: Path, mocker: MockerFixture):
    _ = mocker.patch(
        "PIL.PngImagePlugin.PngImageFile.text", mocker.PropertyMock(return_value=None)
    )
    with pytest.raises(MetadataNotFound):
        _ = Metadata.load(empty_png_path)
