name: Publish to Python Package Indices

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  pypi:
    name: Upload release to the Python Package Index (PyPI)
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install build tools
        run: python3 -m pip install --upgrade build

      - name: Build wheel
        run: python3 -m build

      - name: Publish wheel
        uses: pypa/gh-action-pypi-publish@release/v1
